// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

 /**
  * Creating a sidebar enables you to:
  * - create an ordered group of docs
  * - render a sidebar for each doc of that group
  * - provide next/previous navigation
  *
  * The sidebars can be generated from the filesystem, or explicitly defined here.
  *
  * Create as many sidebars as you want.
  *
  * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
  */
const sidebars = {
  // Autogenerated sidebar for all docs outside of Legal
  documentation: [{ type: 'autogenerated', dirName: '.' }],

  // Manual sidebar for Legal docs
  legal: [
    {
      type: 'category',
      label: 'Legal',
      collapsible: true,
      collapsed: false,
      items: [
        'legal/legal-overview',        // optional Legal Overview page
        'legal/terms',
        'legal/privacy',
        'legal/gdpr',
        'legal/legal-notice',
      ],
    },
  ],
};

export default sidebars;

